// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qtkpEraJg2gN978YDtMYaP
// Component: krho14hlwT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: 2AU0qEyM1oCTCP/component
import DashboardProjectCard from "../../DashboardProjectCard"; // plasmic-import: MYiOb2nF0s/component
import Button from "../../Button"; // plasmic-import: kcMTy-wpYm5s_7/component
import FooterSection from "../../FooterSection"; // plasmic-import: 1ez9I6FpbEKqEg/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../landing_page_starter/plasmic_landing_page_starter.module.css"; // plasmic-import: qtkpEraJg2gN978YDtMYaP/projectcss
import sty from "./PlasmicMember.module.css"; // plasmic-import: krho14hlwT/css

import AppleIcon from "../landing_page_starter/icons/PlasmicIcon__Apple"; // plasmic-import: Zu9y5vY-DbAu23/icon

export type PlasmicMember__VariantMembers = {};

export type PlasmicMember__VariantsArgs = {};
type VariantPropType = keyof PlasmicMember__VariantsArgs;
export const PlasmicMember__VariantProps = new Array<VariantPropType>();

export type PlasmicMember__ArgsType = {};
type ArgPropType = keyof PlasmicMember__ArgsType;
export const PlasmicMember__ArgProps = new Array<ArgPropType>();

export type PlasmicMember__OverridesType = {
  root?: p.Flex<"div">;
  headerHeroSection?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  h2?: p.Flex<"h2">;
  accountSection?: p.Flex<"div">;
  dashboardProjectCard?: p.Flex<typeof DashboardProjectCard>;
  freeBox?: p.Flex<"div">;
  manageButton?: p.Flex<typeof Button>;
  signOutButton?: p.Flex<typeof Button>;
  footerSection?: p.Flex<typeof FooterSection>;
};

export interface DefaultMemberProps {}

function PlasmicMember__RenderFunc(props: {
  variants: PlasmicMember__VariantsArgs;
  args: PlasmicMember__ArgsType;
  overrides: PlasmicMember__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <title key="title">{PlasmicMember.pageMetadata.title}</title>

        <meta
          key="og:title"
          property="og:title"
          content={PlasmicMember.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicMember.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <h2
              data-plasmic-name={"h2"}
              data-plasmic-override={overrides.h2}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2
              )}
            >
              {"會員資訊平台"}
            </h2>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"accountSection"}
            data-plasmic-override={overrides.accountSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.accountSection)}
          >
            <DashboardProjectCard
              data-plasmic-name={"dashboardProjectCard"}
              data-plasmic-override={overrides.dashboardProjectCard}
              className={classNames("__wab_instance", sty.dashboardProjectCard)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <Button
                data-plasmic-name={"manageButton"}
                data-plasmic-override={overrides.manageButton}
                className={classNames("__wab_instance", sty.manageButton)}
                color={"red" as const}
              >
                {"管理帳號"}
              </Button>

              <Button
                data-plasmic-name={"signOutButton"}
                data-plasmic-override={overrides.signOutButton}
                className={classNames("__wab_instance", sty.signOutButton)}
                color={"red" as const}
              >
                {"登出"}
              </Button>
            </p.Stack>
          </p.Stack>

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "h2",
    "accountSection",
    "dashboardProjectCard",
    "freeBox",
    "manageButton",
    "signOutButton",
    "footerSection"
  ],
  headerHeroSection: ["headerHeroSection", "navbar", "h2"],
  navbar: ["navbar"],
  h2: ["h2"],
  accountSection: [
    "accountSection",
    "dashboardProjectCard",
    "freeBox",
    "manageButton",
    "signOutButton"
  ],
  dashboardProjectCard: ["dashboardProjectCard"],
  freeBox: ["freeBox", "manageButton", "signOutButton"],
  manageButton: ["manageButton"],
  signOutButton: ["signOutButton"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  navbar: typeof Navbar;
  h2: "h2";
  accountSection: "div";
  dashboardProjectCard: typeof DashboardProjectCard;
  freeBox: "div";
  manageButton: typeof Button;
  signOutButton: typeof Button;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMember__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMember__VariantsArgs;
    args?: PlasmicMember__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMember__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMember__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMember__ArgProps,
          internalVariantPropNames: PlasmicMember__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMember__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMember";
  } else {
    func.displayName = `PlasmicMember.${nodeName}`;
  }
  return func;
}

export const PlasmicMember = Object.assign(
  // Top-level PlasmicMember renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    h2: makeNodeComponent("h2"),
    accountSection: makeNodeComponent("accountSection"),
    dashboardProjectCard: makeNodeComponent("dashboardProjectCard"),
    freeBox: makeNodeComponent("freeBox"),
    manageButton: makeNodeComponent("manageButton"),
    signOutButton: makeNodeComponent("signOutButton"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicMember
    internalVariantProps: PlasmicMember__VariantProps,
    internalArgProps: PlasmicMember__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "會員資訊平台",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMember;
/* prettier-ignore-end */
