// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qtkpEraJg2gN978YDtMYaP
// Component: 3qFurrWtCkt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: 2AU0qEyM1oCTCP/component
import ValueProp from "../../ValueProp"; // plasmic-import: JJc-2jC6k2mJoy/component
import FooterSection from "../../FooterSection"; // plasmic-import: 1ez9I6FpbEKqEg/component

import { useScreenVariants as useScreenVariantsnCpqQwRKrRf2Hx } from "../landing_page_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: nCpqQwRKrRf2Hx/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../landing_page_starter/plasmic_landing_page_starter.module.css"; // plasmic-import: qtkpEraJg2gN978YDtMYaP/projectcss
import sty from "./PlasmicPlatform.module.css"; // plasmic-import: 3qFurrWtCkt/css

import TargetIcon from "../landing_page_starter/icons/PlasmicIcon__Target"; // plasmic-import: Wt4zs8noN7sd2H/icon
import CheckIcon from "../landing_page_starter/icons/PlasmicIcon__Check"; // plasmic-import: gHCuOW8JEryqrm/icon
import CheckCircleIcon from "../landing_page_starter/icons/PlasmicIcon__CheckCircle"; // plasmic-import: _QAU6Sxfpz1Lu0/icon
import StrongIcon from "../landing_page_starter/icons/PlasmicIcon__Strong"; // plasmic-import: nO_1wxfmPKvWbo/icon
import WandIcon from "../landing_page_starter/icons/PlasmicIcon__Wand"; // plasmic-import: iQv5jNrYURIoDO/icon

export type PlasmicPlatform__VariantMembers = {};

export type PlasmicPlatform__VariantsArgs = {};
type VariantPropType = keyof PlasmicPlatform__VariantsArgs;
export const PlasmicPlatform__VariantProps = new Array<VariantPropType>();

export type PlasmicPlatform__ArgsType = {};
type ArgPropType = keyof PlasmicPlatform__ArgsType;
export const PlasmicPlatform__ArgProps = new Array<ArgPropType>();

export type PlasmicPlatform__OverridesType = {
  root?: p.Flex<"div">;
  headerHeroSection?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  aboutSection?: p.Flex<"div">;
  columns?: p.Flex<"div">;
  processSection?: p.Flex<"div">;
  footerSection?: p.Flex<typeof FooterSection>;
};

export interface DefaultPlatformProps {}

function PlasmicPlatform__RenderFunc(props: {
  variants: PlasmicPlatform__VariantsArgs;
  args: PlasmicPlatform__ArgsType;
  overrides: PlasmicPlatform__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnCpqQwRKrRf2Hx()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <title key="title">{"會員資訊平台"}</title>

        <meta key="og:title" property="og:title" content={"會員資訊平台"} />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={"會員資訊平台"}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__cJt7W
              )}
            >
              {"價目表"}
            </h2>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"aboutSection"}
            data-plasmic-override={overrides.aboutSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.aboutSection)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__nmEDq)}>
                <div className={classNames(projectcss.all, sty.freeBox__r2EG)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__gIfpR
                    )}
                  >
                    {"結構估算"}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yyVmh
                    )}
                  >
                    {"鋼筋、模板、混凝土數量估算、鋼筋施工圖檢視​"}
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__uBswg)}>
                <div className={classNames(projectcss.all, sty.freeBox__aQuyk)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__cTqtd
                    )}
                  >
                    {"裝修估算​"}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pBfJt
                    )}
                  >
                    {"室內及外裝修數量、分層、分戶​"}
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__iQXg)}>
                <div className={classNames(projectcss.all, sty.freeBox__nshmG)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__kPyow
                    )}
                  >
                    {"工程預算書及標單編列​"}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fBqXs
                    )}
                  >
                    {"室內及外裝修數量、分層、分戶​"}
                  </div>
                </div>
              </div>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"processSection"}
            data-plasmic-override={overrides.processSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.processSection)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__cqrI6
              )}
            >
              {"估價流程"}
            </h2>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1WtNa)}
            >
              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__sKApt)}
                description={"此階段以概算估價為主。"}
                flatIcon={true}
                icon={
                  <TargetIcon
                    className={classNames(projectcss.all, sty.svg__wuIu0)}
                    role={"img"}
                  />
                }
                title={"規劃階段估價"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__fZxvj)}
                description={"又稱底價估價，此階段可分初步設計及完整設計"}
                flatIcon={true}
                icon={
                  <CheckIcon
                    className={classNames(projectcss.all, sty.svg___8OQg9)}
                    role={"img"}
                  />
                }
                title={"設計階段估價"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__ounUo)}
                description={"又稱投標估價，此階段以概算估價或詳細估價為主。"}
                flatIcon={true}
                icon={
                  <CheckCircleIcon
                    className={classNames(projectcss.all, sty.svg___0OwJm)}
                    role={"img"}
                  />
                }
                title={"投標階段估價"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__woXdo)}
            >
              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp___4EnGg)}
                description={"又稱施工估價，此階段以詳細估價為主。"}
                flatIcon={true}
                icon={
                  <StrongIcon
                    className={classNames(projectcss.all, sty.svg__f3PR)}
                    role={"img"}
                  />
                }
                title={"施工階段估價"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__op5Ws)}
                description={"又稱期別估價或估驗，此階段以詳細估價為主。"}
                flatIcon={true}
                icon={
                  <WandIcon
                    className={classNames(projectcss.all, sty.svg__hXcm6)}
                    role={"img"}
                  />
                }
                title={"驗收階段估價"}
              />
            </p.Stack>
          </p.Stack>

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "aboutSection",
    "columns",
    "processSection",
    "footerSection"
  ],
  headerHeroSection: ["headerHeroSection", "navbar"],
  navbar: ["navbar"],
  aboutSection: ["aboutSection", "columns"],
  columns: ["columns"],
  processSection: ["processSection"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  navbar: typeof Navbar;
  aboutSection: "div";
  columns: "div";
  processSection: "div";
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPlatform__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPlatform__VariantsArgs;
    args?: PlasmicPlatform__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPlatform__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPlatform__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPlatform__ArgProps,
          internalVariantPropNames: PlasmicPlatform__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPlatform__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPlatform";
  } else {
    func.displayName = `PlasmicPlatform.${nodeName}`;
  }
  return func;
}

export const PlasmicPlatform = Object.assign(
  // Top-level PlasmicPlatform renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    aboutSection: makeNodeComponent("aboutSection"),
    columns: makeNodeComponent("columns"),
    processSection: makeNodeComponent("processSection"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicPlatform
    internalVariantProps: PlasmicPlatform__VariantProps,
    internalArgProps: PlasmicPlatform__ArgProps
  }
);

export default PlasmicPlatform;
/* prettier-ignore-end */
