// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qtkpEraJg2gN978YDtMYaP
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : ("/* CSS snippet */\r\n\r\n.vertical-word{\r\n    writing-mode: vertical-rl;\r\n}\r\n\r\n.modal-pop{\r\n    animation-name: popUp;\r\n    animation-duration:1s;\r\n}\r\n\r\n@keyframes popUp{\r\n    from{\r\n        opacity:0;\r\n        transform: translate(0%,-50%);\r\n    }\r\n    to{\r\n        opacity:1;\r\n        transform:translate(0%,0%);\r\n}" as const)
      }
    >
      {children}
    </EmbedCss>
  );
}
