// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qtkpEraJg2gN978YDtMYaP
// Component: WueZ8IvzTBv
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsnCpqQwRKrRf2Hx } from "../landing_page_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: nCpqQwRKrRf2Hx/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../landing_page_starter/plasmic_landing_page_starter.module.css"; // plasmic-import: qtkpEraJg2gN978YDtMYaP/projectcss
import sty from "./PlasmicProjectCardDetailReverse.module.css"; // plasmic-import: WueZ8IvzTBv/css

export type PlasmicProjectCardDetailReverse__VariantMembers = {};

export type PlasmicProjectCardDetailReverse__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjectCardDetailReverse__VariantsArgs;
export const PlasmicProjectCardDetailReverse__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjectCardDetailReverse__ArgsType = {
  projectImage?: React.ReactNode;
  projectSubImage?: React.ReactNode;
  title?: React.ReactNode;
  description?: React.ReactNode;
  locationTitle?: React.ReactNode;
  location?: React.ReactNode;
  categoryTitle?: React.ReactNode;
  category?: React.ReactNode;
};

type ArgPropType = keyof PlasmicProjectCardDetailReverse__ArgsType;
export const PlasmicProjectCardDetailReverse__ArgProps = new Array<ArgPropType>(
  "projectImage",
  "projectSubImage",
  "title",
  "description",
  "locationTitle",
  "location",
  "categoryTitle",
  "category"
);

export type PlasmicProjectCardDetailReverse__OverridesType = {
  root?: p.Flex<"div">;
  h3?: p.Flex<"h3">;
};

export interface DefaultProjectCardDetailReverseProps {
  projectImage?: React.ReactNode;
  projectSubImage?: React.ReactNode;
  title?: React.ReactNode;
  description?: React.ReactNode;
  locationTitle?: React.ReactNode;
  location?: React.ReactNode;
  categoryTitle?: React.ReactNode;
  category?: React.ReactNode;
  className?: string;
}

function PlasmicProjectCardDetailReverse__RenderFunc(props: {
  variants: PlasmicProjectCardDetailReverse__VariantsArgs;
  args: PlasmicProjectCardDetailReverse__ArgsType;
  overrides: PlasmicProjectCardDetailReverse__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnCpqQwRKrRf2Hx()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__y10O9)}
      >
        <h3
          data-plasmic-name={"h3"}
          data-plasmic-override={overrides.h3}
          className={classNames(projectcss.all, projectcss.h3, sty.h3)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "高雄七期改建工程",
            value: args.title
          })}
        </h3>

        <div className={classNames(projectcss.all, sty.freeBox__afbay)}>
          {p.renderPlasmicSlot({
            defaultContents:
              "此次改建案總經費3.38 億元。預期新增五百坪室內空間 。從前期的標案，到最後的完工，所有的估算皆完整評估。該設施的總面積為 140,000 平方公尺。 具體工作範圍包括機械、電氣、管道和消防的成本分析。​",
            value: args.description
          })}
        </div>

        <h4
          className={classNames(projectcss.all, projectcss.h4, sty.h4__wjMsx)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "地點:",
            value: args.locationTitle
          })}
        </h4>

        <div className={classNames(projectcss.all, sty.freeBox__leYjS)}>
          {p.renderPlasmicSlot({
            defaultContents: "高雄",
            value: args.location
          })}
        </div>

        <h4
          className={classNames(projectcss.all, projectcss.h4, sty.h4___7Mzws)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "項目:",
            value: args.categoryTitle
          })}
        </h4>

        <div className={classNames(projectcss.all, sty.freeBox__msRBe)}>
          {p.renderPlasmicSlot({
            defaultContents: "結構與裝修數量估算",
            value: args.category
          })}
        </div>
      </p.Stack>

      {true ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__xmdyx)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__fDeOd)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vZfxm)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/laziness_demo/images/bimHouse.webp",
                    fullWidth: 4730,
                    fullHeight: 2405,
                    aspectRatio: undefined
                  }}
                />
              ),

              value: args.projectImage
            })}
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__p29A8)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__v9RAk)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/laziness_demo/images/hallway.webp",
                      fullWidth: 3024,
                      fullHeight: 4032,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pRB9)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/laziness_demo/images/office2.webp",
                      fullWidth: 6720,
                      fullHeight: 4480,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ll5Zg)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/laziness_demo/images/hallway.webp",
                      fullWidth: 3024,
                      fullHeight: 4032,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__twU0V)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/laziness_demo/images/office2.webp",
                      fullWidth: 6720,
                      fullHeight: 4480,
                      aspectRatio: undefined
                    }}
                  />
                </React.Fragment>
              ),
              value: args.projectSubImage
            })}
          </div>
        </p.Stack>
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h3"],
  h3: ["h3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h3: "h3";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjectCardDetailReverse__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjectCardDetailReverse__VariantsArgs;
    args?: PlasmicProjectCardDetailReverse__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjectCardDetailReverse__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProjectCardDetailReverse__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProjectCardDetailReverse__ArgProps,
          internalVariantPropNames:
            PlasmicProjectCardDetailReverse__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProjectCardDetailReverse__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectCardDetailReverse";
  } else {
    func.displayName = `PlasmicProjectCardDetailReverse.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectCardDetailReverse = Object.assign(
  // Top-level PlasmicProjectCardDetailReverse renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),

    // Metadata about props expected for PlasmicProjectCardDetailReverse
    internalVariantProps: PlasmicProjectCardDetailReverse__VariantProps,
    internalArgProps: PlasmicProjectCardDetailReverse__ArgProps
  }
);

export default PlasmicProjectCardDetailReverse;
/* prettier-ignore-end */
