// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAccountCard,
  DefaultAccountCardProps,
} from "./plasmic/laziness_demo/PlasmicAccountCard";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { UserDetails } from "../types";

export interface AccountCardProps extends DefaultAccountCardProps {}

function AccountCard_(
  props: AccountCardProps,
  ref: HTMLElementRefOf<"div">
) {
  return (
    <PlasmicAccountCard
      root={{ ref }}
      {...props}
      // company={user.company}
      // name={user.user_name}
      // phoneNumber={user.phone}
      // address={user.address}
      // email={user.email}
    />
  );
}

const AccountCard = React.forwardRef(AccountCard_);
export default AccountCard;
