// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicContactForm,
  DefaultContactFormProps,
} from "./plasmic/laziness_demo/PlasmicContactForm";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import emailjs from "@emailjs/browser";

export interface ContactFormProps extends DefaultContactFormProps {}

function ContactForm_(props: ContactFormProps, ref: HTMLElementRefOf<"div">) {
  // const form = React.useRef();
  const handleSendEmail = (e: any) => {
    e.preventDefault();
    console.log("eTarget", e.target);

    emailjs
      .sendForm(
        "service_w58hfa6",
        "template_wwpri6t",
        e.target,
        "L62iNBtBc3zDZPNft"
      )
      .then(
        (result) => {
          console.log("成功寄送郵件", result.text);
        },
        (error) => {
          console.log("郵件寄送失敗", error.text);
        }
      );
    e.target.reset();
  };

  return (
    <PlasmicContactForm
      root={{ ref }}
      {...props}
      requestForm={{ onSubmit: handleSendEmail }}
      fromName={{ props: { name: "from_name", type: "text" } }}
      phoneNumber={{ props: { name: "phoneNumber", type: "tel" } }}
      fromEmail={{ props: { name: "from_email", type: "email" } }}
      // sendEmail={{
      //   onClick: handleSendEmail,
      // }}
    />
  );
}

const ContactForm = React.forwardRef(ContactForm_);
export default ContactForm;
