// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDashboardProjectCard,
  DefaultDashboardProjectCardProps,
} from "./plasmic/laziness_demo/PlasmicDashboardProjectCard";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface DashboardProjectCardProps
  extends DefaultDashboardProjectCardProps {}

function DashboardProjectCard_(
  props: DashboardProjectCardProps,
  ref: HTMLElementRefOf<"div">
) {
  const [isProjectDetailView, setIsProjectDetailView] = React.useState(false);

  return (
    <PlasmicDashboardProjectCard
      isProjectDetailView={isProjectDetailView}
      root={{ ref }}
      {...props}
      toggleButton={{
        onClick: () => setIsProjectDetailView(!isProjectDetailView),
      }}
    />
  );
}

const DashboardProjectCard = React.forwardRef(DashboardProjectCard_);
export default DashboardProjectCard;
